# Generated by Django 4.0.3 on 2022-03-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenDetails',
            fields=[
                ('CitizenId', models.AutoField(primary_key=True, serialize=False)),
                ('CitizenFirstName', models.CharField(max_length=50)),
                ('CitizenLastName', models.CharField(max_length=50)),
                ('CitizenDOB', models.DateField(max_length=8)),
                ('CitizenAddress', models.CharField(max_length=100)),
                ('CitizenCity', models.CharField(max_length=50)),
                ('CitizenZipCode', models.IntegerField(max_length=20)),
                ('CitizenLandLine', models.CharField(max_length=10)),
                ('CitizenCellular', models.IntegerField(max_length=10)),
                ('CitizenInfected', models.BooleanField()),
                ('CitizenConditions', models.CharField(max_length=100)),
            ],
        ),
    ]
