# Generated by Django 4.0.3 on 2022-03-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_alter_citizendetails_citizencellular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizendetails',
            name='CitizenCity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='citizendetails',
            name='CitizenFirstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='citizendetails',
            name='CitizenLandLine',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='citizendetails',
            name='CitizenLastName',
            field=models.CharField(max_length=100),
        ),
    ]
