# Generated by Django 4.0.3 on 2022-03-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_alter_citizendetails_citizencity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizendetails',
            name='CitizenCity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='citizendetails',
            name='CitizenFirstName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='citizendetails',
            name='CitizenLandLine',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='citizendetails',
            name='CitizenLastName',
            field=models.CharField(max_length=50),
        ),
    ]
